project:
  type: book

book:
  author: "chsh2.github.io"
  sidebar:
    tools:
      - icon: github
        href: https://github.com/chsh2/texture_vfx_control
      - icon: bluesky
        href: https://bsky.app/profile/chsh2.bsky.social
      - icon: twitter
        href: https://x.com/chaosinism
      - icon: youtube
        href: http://www.youtube.com/@chaosinism9491
