# Blender Settings {.unnumbered}

This chapter explores the Blender settings that may have a significant impact on the add-on results.

## Image Texture Node

The [Image Texture Node](https://docs.blender.org/manual/en/latest/render/shader_nodes/textures/image.html) which contains the media has the following settings relevant to some visual effects:

- **Interpolation**: When using effects of the pixelated style, it is recommended to set this option to `Closest`. Otherwise, using `Smart` or `Cubic` will make the image smoother.
- **Extension**: The Distortion effects may warp the image, leaving blank areas. This option determines whether the image is extended to fill these areas.

These options are also displayed in the add-on side panel to make modifications easier.

## Material Settings

The EEVEE engine has two methods, `Dithered` and `Blended`, to handle transparency. Each method has its own benefits and drawbacks. Please refer to the [official document](https://docs.blender.org/manual/en/latest/render/eevee/material_settings.html).

## Render Settings

The EEVEE engine has a [sampling option](https://docs.blender.org/manual/en/latest/render/eevee/render_settings/sampling.html) named `Temporal Reprojection` to reduce noise during the preview. However, this can result in severe artifacts when previewing a video texture. It is recommended to disable this option.